name: "Terraform Auto Apply"

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    name: Terraform Plan and Apply
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Debug OIDC Token
        run: |
          echo "Retrieving OIDC token..."
          curl -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
               "$ACTIONS_ID_TOKEN_REQUEST_URL" > oidc-token.json
          cat oidc-token.json

      # Step 2: Configure AWS credentials with Assume Role
      - name: Configure AWS Credentials
        id: aws-creds
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::730335337132:role/vpn-edangla-role
          aws-region: "ca-central-1"

      # Step 3: Install Terraform CLI
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.5

      # Step 4: Initialize Terraform with Terraform Cloud backend
      - name: Terraform Init
        run: terraform init

      # Step 5: Terraform Plan
      - name: Terraform Plan
        run: terraform plan -out=tfplan

      # Step 6: Terraform Apply (Auto-approve)
      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
        env:
          TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
